-- supabase/migrations/0002_anonymous_usage.sql

-- Drop the existing table if it exists to ensure a clean slate, 
-- as the previous schema was incorrect for the intended logic.
DROP TABLE IF EXISTS public.sc_anonymous_usage;

-- Recreate the table with the correct schema that allows tracking multiple
-- conversion events per user, which is required to check usage within a time window.
CREATE TABLE public.sc_anonymous_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add comments for clarity
COMMENT ON TABLE public.sc_anonymous_usage IS 'Tracks anonymous conversions to enforce daily limits.';
COMMENT ON COLUMN public.sc_anonymous_usage.ip_hash IS 'SHA256 hash of the user''s IP address.';
COMMENT ON COLUMN public.sc_anonymous_usage.created_at IS 'Timestamp of the conversion event.';

-- Enable Row Level Security
ALTER TABLE public.sc_anonymous_usage ENABLE ROW LEVEL SECURITY;

-- Define access policies
CREATE POLICY "Allow public read access"
ON public.sc_anonymous_usage
FOR SELECT
USING (true);

CREATE POLICY "Allow anonymous insert access"
ON public.sc_anonymous_usage
FOR INSERT
WITH CHECK (true);

-- Add indexes for performance on columns that are frequently queried
CREATE INDEX IF NOT EXISTS idx_sc_anonymous_usage_ip_hash ON public.sc_anonymous_usage(ip_hash);
CREATE INDEX IF NOT EXISTS idx_sc_anonymous_usage_created_at ON public.sc_anonymous_usage(created_at);
